[general]
import = ["~/.dotfiles/alacritty/alacritty.toml"]

[window]
startup_mode = "SimpleFullscreen"

[terminal]

[terminal.shell]
program = "/bin/zsh"
args = ["--login", "-c", "tmux new-session -A -D -s main"]

[keyboard]
bindings = [
  { key = "N",        mods = "Command|Shift", command = { program = "/opt/homebrew/bin/alacritty", args = ["msg", "create-window", "-e", "/bin/zsh", "--login", "-c", "tmux-sessions servers"] } }, # open session in new window with all sessions menu across servers
]
