[general]
import = ["~/.dotfiles/alacritty/alacritty.toml"]

[window]
startup_mode = "Fullscreen"

[terminal]

[terminal.shell]
program = "/bin/bash"
args = ["--login", "-c", "tmux new-session -A -D -s main"]

[keyboard]
bindings = [
  { key = "N",        mods = "Command|Shift", command = { program = "/usr/bin/alacritty", args = ["msg", "create-window", "-e", "/bin/bash", "--login", "-c", "tmux-sessions --all"] } }, # open session in new window with all sessions menu across servers
]
