# Prompt format
format = """
$username\
$hostname\
$directory\
$golang\
$java\
$nodejs\
$python\
$rust\
$cmd_duration\
$line_break\
$character"""

[character]
format = "$symbol\u00A0"
success_symbol = "[](white)"
error_symbol = "[](red)"
vicmd_symbol = "[](white)"

[directory]
style = "blue bold"
truncation_length = 5

[golang]
format = "[${symbol}](white)"
symbol = " "

[java]
format = "[${symbol}](white)"
symbol = " "

[nodejs]
format = "[$symbol}](white)"
symbol = "󰎙 "

[python]
format = "[${symbol}](white)"
symbol = " "

[rust]
format = "[${symbol}](white)"
symbol = " "
